project:
  type: manuscript
  pre-render: "./cleanup-knit.sh"
  post-render: "./cleanup-knit.sh"
  output-dir: ../docs
  render:
    - index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: show
    highlight-style: tango
    number-sections: true
    title: "Minneapolis Spatial Analysis"
