project:
  type: website

website:
  title: "Minneapolis Spatial Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: methods.qmd
        text: Methods
      - href: results.qmd
        text: Results

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show
