project:
  type: website

website:
  title: "Minneapolis Spatial Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: methods.qmd
        text: Methods
      - href: spatial_regression.qmd
        text: Spatial Regression
      - href: moran_lisa.qmd
        text: Moran's I and LISA

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show
