project:
  type: website
  pre-render: "./cleanup-knit.sh"
  post-render: "./cleanup-knit.sh"

website:
  title: "Minneapolis Spatial Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: methods.qmd
        text: Methods
      - href: spatial_regression.qmd
        text: Spatial Regression
      - href: moran_lisa.qmd
        text: Moran's I and LISA

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: show
    highlight-style: tango
    number-sections: true
